# WARNING: this file was autogenerated by generate-included-image.js
# using
#   npm run add:included -- 8.7.0-updated cypress/browsers:node16.15.1-chrome91-ff89
set e+x

LOCAL_NAME=cypress/included:8.7.0-updated
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
