# WARNING: this file was autogenerated by generate-included-image.js
# using
#   npm run add:included -- 10.1.0 cypress/browsers:node16.15.1-chrome100-ff98
set e+x

LOCAL_NAME=cypress/included:10.1.0
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
